@baseUrl = http://localhost:5000


################################################## MadTech
GET {{baseUrl}}/MadTech/GetLanguages
#####
GET {{baseUrl}}/MadTech/GetRooms
#####
GET {{baseUrl}}/MadTech/GetUserLogin
Content-type: application/json

{
   "userName": "abc",
   "password": "abc"
}
#####
GET {{baseUrl}}/MadTech/GetUsers
#####
POST {{baseUrl}}/MadTech/AddUser
Content-type: application/json

{
   "mail": "abc",
   "userName": "abc",
   "password": "abc",
   "countryName": "abc",
   "firstName": "abc",
   "lastName": "abc"
}
#####
POST {{baseUrl}}/MadTech/CreateRoom?RoomName=abc
Content-type: application/json

{
   "id": 1,
   "userName": "abc",
   "twilSid": "abc",
   "authTkn": "abc"
}
#####
